In [1]:
import jieba
import gensim
import re
import numpy as np
import pandas as pd

In [2]:
jieba.load_userdict('user_defined_dict.txt')

Building prefix dict from the default dictionary ...
Dumping model to file cache /var/folders/lp/3p8p8yx17vs3nf76dxw6kx_m0000gn/T/jieba.cache
Loading model cost 0.861 seconds.
Prefix dict has been built successfully.


In [3]:
print(jieba.user_word_tag_tab)

{'UNNC': 'n', 'unnc': 'n', '宁诺': 'n', '诺圈': 'n', 'Nottinghome': 'n', 'nottinghome': 'n'}


In [4]:
data = pd.read_excel('../weiboData.xlsx', 'sheet1', encoding='utf-8')

In [5]:
# for index, row in data.iterrows():
#     data.loc[index, 'seg'] = re.sub('\u3000', '', data.loc[index, 'text'])
#     data.loc[index, 'seg'] = re.sub('\s+', ' ', data.loc[index, 'text'])
#     data.loc[index, 'seg'] = re.sub('[a-zA-Z0-9’!"#$·_－＿＊%&\'()*+,-./:;<=>?@：（），。?★、…【】《》？“”‘’！[\\]^_`{|}~\s]+', " ", data.loc[index, 'text'])
    
# data.head()
# data.info()


In [6]:
def get_stop_words(path=r'./停用词汇总.txt'):
    file = open(path, 'r', encoding='utf-8').read().split('\n')
    return set(file)

def rm_tokens(words, stwlist):
    words_list = list(words)
    stop_words = stwlist
    for i in range(words_list.__len__())[::-1]:
        # 去除停用词
        if words_list[i] in stop_words:
            words_list.pop(i)
        # 去除数字
        elif words_list[i].isdigit():
            words_list.pop(i)
        # 去除单个字符
        elif len(words_list[i]) == 1:
            words_list.pop(i)
        # 去除空格
        elif words_list[i] == " ":
            words_list.pop(i)
    return words_list

In [7]:
stwlist = get_stop_words()

In [8]:
jieba.enable_parallel(64)
data['seg'] = data['text'].apply(lambda i : rm_tokens(jieba.cut(i, cut_all=False), stwlist))
# data['seg'] =[' '.join(i) for i in data['seg']]


In [9]:
str_list = []
str_list = data['text']

In [10]:
str_list

0                                     8.21中午求拼车南安普顿大学二手社区
1       如今二手房市场惨淡的原因你知道吗？这是否反映了当今楼市的残酷现实？#二手房#涨知识##快手#...
2          伊犁理论上说，每卖出一套新房，就会多出一套二手房。但是二手房价似乎一点都没跌啊？你有感觉么？
3                #美国##我的vlog生活##福特野马#买二手车要砍价！L小水水iii的微博视频
4       周二休息周一晚就跑去鱼鱼家度假叻测试完麦克风和二手音响都没毛病之后就困困了抱着小恐龙等鱼鱼下...
                              ...                        
7874    #房产微盘点#最近，南京高考成绩出炉，不少学区房家长开始新一轮焦虑，学区房一直是社会热点，但...
7875    #粉笔挖媒#今日聚焦社会热点——屡被质疑的青霉面包做汉堡，道歉不能代替严惩。小粉笔和你一起进...
7876    【老人摔倒敢不敢扶？遇到小偷敢不敢追？民事检察官这样说……】近年来，老人倒地扶不扶、遇见小偷...
7877    #社会热点#据媒体报道，腾讯将牵头合并斗鱼和虎牙的谈判。据新京报6月11日报道，腾讯正推动斗...
7878    @秦淮发布#民法典与百姓生活#【老人摔倒敢不敢扶？遇到小偷敢不敢追？民事检察官这样说……】近...
Name: text, Length: 7879, dtype: object

In [11]:
corpus_list = str_list[0:20]

In [12]:
texts_list=[]
for sentence in corpus_list:
    sentence_list=[ word for word in rm_tokens(jieba.cut(sentence, cut_all=False), stwlist)]
    texts_list.append(sentence_list)
    
dictionary=gensim.corpora.Dictionary(texts_list)

In [13]:
print(dictionary)
print(dictionary.token2id)

Dictionary(253 unique tokens: ['8.21', '中午', '二手', '南安普顿', '大学']...)
{'8.21': 0, '中午': 1, '二手': 2, '南安普顿': 3, '大学': 4, '拼车': 5, '社区': 6, '二手房': 7, '当今': 8, '快手': 9, '惨淡': 10, '楼市': 11, '残酷': 12, '现实': 13, '白话': 14, '视频': 15, '闲哥': 16, '一套': 17, '伊犁': 18, '卖出': 19, '多出': 20, '新房': 21, '理论': 22, 'iii': 23, 'vlog': 24, '二手车': 25, '小水水': 26, '微博': 27, '生活': 28, '砍价': 29, '福特': 30, '美国': 31, '野马': 32, '下班': 33, '休息': 34, '午觉': 35, '半夜': 36, '周一': 37, '周二': 38, '困困': 39, '差点': 40, '度假': 41, '开封': 42, '恐龙': 43, '抽走': 44, '新品': 45, '早茶': 46, '毛病': 47, '测试': 48, '电影': 49, '电影票': 50, '睡着': 51, '起不来': 52, '还好': 53, '进到': 54, '迟到': 55, '迷迷糊糊': 56, '隔壁': 57, '音响': 58, '顺便': 59, '鱼家': 60, '麦克风': 61, 'BfiCTCiSxa8': 62, '两江': 63, '四岸': 64, '房产': 65, '抖音': 66, '看房': 67, '重庆': 68, 'FJ40': 69, '兰德': 70, '改装': 71, '疯狂': 72, '越野': 73, '部落': 74, '酷路泽': 75, 'To': 76, 'pb': 77, '一颗': 78, '三点': 79, '不好': 80, '两份': 81, '互动': 82, '凌晨': 83, '去年': 84, '后悔': 85, '周边': 86, '夏天': 87, '将来': 88, '年轻': 89, '床上': 90, '心碎

In [14]:
texts_list

[['8.21', '中午', '拼车', '南安普顿', '大学', '二手', '社区'],
 ['二手房',
  '惨淡',
  '当今',
  '楼市',
  '残酷',
  '现实',
  '二手房',
  '快手',
  '快手',
  '闲哥',
  '白话',
  '快手',
  '视频'],
 ['伊犁', '理论', '卖出', '一套', '新房', '多出', '一套', '二手房', '二手房'],
 ['美国', 'vlog', '生活', '福特', '野马', '二手车', '砍价', '小水水', 'iii', '微博', '视频'],
 ['周二',
  '休息',
  '周一',
  '鱼家',
  '度假',
  '测试',
  '麦克风',
  '二手',
  '音响',
  '毛病',
  '困困',
  '恐龙',
  '下班',
  '迷迷糊糊',
  '睡着',
  '半夜',
  '恐龙',
  '抽走',
  '隔壁',
  '进到',
  '中午',
  '早茶',
  '顺便',
  '电影票',
  '午觉',
  '起不来',
  '差点',
  '迟到',
  '还好',
  '电影',
  '电影',
  '开封',
  '新品'],
 ['重庆', '房产', '二手房', '两江', '四岸', '房产', '看房', 'BfiCTCiSxa8', '抖音'],
 ['改装', '越野', '部落', 'FJ40', '兰德', '酷路泽', '改装', '疯狂', '二手车'],
 ['去年',
  '空调',
  '凌晨',
  '三点',
  '床上',
  '一颗',
  '生日',
  '祝福',
  '互动',
  '感叹',
  '年轻',
  '死死的',
  '后悔',
  '两份',
  'pb',
  '留恋',
  '二手',
  '夏天',
  '留点',
  '纪念品',
  '不好',
  '心碎',
  '成渣',
  'To',
  '将来',
  '随便',
  '周边'],
 ['海淘求', 'TF', '阿玛尼', 'YSL', '新色', '货团', '二手', '贩子', '别来', '价钱'],
 ['房子',
  '飓风',
  '吹倒',
  '美

In [15]:
corpus = [dictionary.doc2bow(doc) for doc in texts_list]
print(corpus)

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1)], [(7, 2), (8, 1), (9, 3), (10, 1), (11, 1), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1)], [(7, 2), (17, 2), (18, 1), (19, 1), (20, 1), (21, 1), (22, 1)], [(15, 1), (23, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 1)], [(1, 1), (2, 1), (33, 1), (34, 1), (35, 1), (36, 1), (37, 1), (38, 1), (39, 1), (40, 1), (41, 1), (42, 1), (43, 2), (44, 1), (45, 1), (46, 1), (47, 1), (48, 1), (49, 2), (50, 1), (51, 1), (52, 1), (53, 1), (54, 1), (55, 1), (56, 1), (57, 1), (58, 1), (59, 1), (60, 1), (61, 1)], [(7, 1), (62, 1), (63, 1), (64, 1), (65, 2), (66, 1), (67, 1), (68, 1)], [(25, 1), (69, 1), (70, 1), (71, 2), (72, 1), (73, 1), (74, 1), (75, 1)], [(2, 1), (76, 1), (77, 1), (78, 1), (79, 1), (80, 1), (81, 1), (82, 1), (83, 1), (84, 1), (85, 1), (86, 1), (87, 1), (88, 1), (89, 1), (90, 1), (91, 1), (92, 1), (93, 1), (94, 1), (95, 1), (96, 1), (97, 1), (98, 1), (99, 1), (100, 1), (101, 1)], [(2, 1), (102, 

In [16]:
tfidf = gensim.models.TfidfModel(corpus)

In [17]:
# 分析测试文档与已存在的每个训练文本的相似度
index = gensim.similarities.SparseMatrixSimilarity(tfidf[corpus], 
                                                   num_features=len(dictionary.keys()))

In [49]:
# 使用tf-idf算法对上面的语料库进行建模，识别不同文本的相似度。
similarity_matrix = []


# for i in range(0, 3):
#     test_string = data['text'][i]
#     test_doc_list = [word for word in jieba.cut(test_string)]
#     test_doc_vec = dictionary.doc2bow(test_doc_list)
#     similarity[i] = index[tfidf[test_doc_vec]]

print(similarity_matrix)
# print(np.around(similarity, 4))

[]


In [19]:
tfidf.save("tfidf.model")

In [23]:
np.savetxt('matrixFile.txt', similarity, fmt='%f')

In [38]:
test_string = data['text'][1]

In [39]:
test_doc_list = [word for word in jieba.cut(test_string)]

In [40]:
test_doc_vec = dictionary.doc2bow(test_doc_list)

In [44]:
similarity = index[tfidf[test_doc_vec]]
similarity

array([0.        , 0.9999999 , 0.11877163, 0.02388704, 0.        ,
       0.05879446, 0.        , 0.        , 0.        , 0.03996632,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.02819041],
      dtype=float32)

In [47]:
type(similarity_matrix)

numpy.ndarray

In [51]:
similarity_matrix.append(similarity)

In [52]:
similarity_matrix

[array([0.        , 0.9999999 , 0.11877163, 0.02388704, 0.        ,
        0.05879446, 0.        , 0.        , 0.        , 0.03996632,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.02819041],
       dtype=float32)]

In [53]:
test_string = data['text'][0]
test_doc_list = [word for word in jieba.cut(test_string)]
test_doc_vec = dictionary.doc2bow(test_doc_list)
similarity2 = index[tfidf[test_doc_vec]]

In [55]:
similarity_matrix.append(similarity2)
similarity_matrix

[array([0.        , 0.9999999 , 0.11877163, 0.02388704, 0.        ,
        0.05879446, 0.        , 0.        , 0.        , 0.03996632,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.02819041],
       dtype=float32),
 array([1.0000001 , 0.        , 0.        , 0.        , 0.04568831,
        0.        , 0.        , 0.00448577, 0.00748911, 0.00439955,
        0.01289549, 0.00580791, 0.        , 0.        , 0.00134752,
        0.01002401, 0.01119238, 0.        , 0.        , 0.        ],
       dtype=float32),
 array([1.0000001 , 0.        , 0.        , 0.        , 0.04568831,
        0.        , 0.        , 0.00448577, 0.00748911, 0.00439955,
        0.01289549, 0.00580791, 0.        , 0.        , 0.00134752,
        0.01002401, 0.01119238, 0.        , 0.        , 0.        ],
       dtype=float32)]

In [56]:
s = np.mat(similarity_matrix)

In [57]:
s

matrix([[0.        , 0.9999999 , 0.11877163, 0.02388704, 0.        ,
         0.05879446, 0.        , 0.        , 0.        , 0.03996632,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.02819041],
        [1.0000001 , 0.        , 0.        , 0.        , 0.04568831,
         0.        , 0.        , 0.00448577, 0.00748911, 0.00439955,
         0.01289549, 0.00580791, 0.        , 0.        , 0.00134752,
         0.01002401, 0.01119238, 0.        , 0.        , 0.        ],
        [1.0000001 , 0.        , 0.        , 0.        , 0.04568831,
         0.        , 0.        , 0.00448577, 0.00748911, 0.00439955,
         0.01289549, 0.00580791, 0.        , 0.        , 0.00134752,
         0.01002401, 0.01119238, 0.        , 0.        , 0.        ]],
       dtype=float32)

In [58]:
np.savetxt('matrixFile.txt', s, fmt='%f')